[[cells]]
name = "auth"
enable_type_id = false
location = { file = "../../deps/auth" }

[[cells]]
name = "funding-lock"
enable_type_id = true
location = { file = "../../build/release/funding-lock" }

[[cells]]
name = "commitment-lock"
enable_type_id = true
location = { file = "../../build/release/commitment-lock" }

[lock]
code_hash = "0x36c971b8d41fbd94aabca77dc75e826729ac98447b46f91e00796155dddb0d29"
args = "0x66712ae36e89b0e796155d004bebe2540ee7dfc9"
hash_type = "data1"

# For unlocking inputs with multisig lock script
[multisig_config]
sighash_addresses = [
  "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2hvk2yvt998w799ra8t73gunvrjrlw4agv2t7np",
  "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2j24grqwjffj4ys2k2wtytfcvzhcf8tugut5v4n",
  "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2u7q5rqr3nam68g2wfel9365l855m7fcg58j52a",
  "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqv8rhlzfvjl22jhg6j7046x9a6xph3vvwq2luq73",
  "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvsd9auv0wsq0a9mmp8f6hqax3fg8430mstg754t",
]
require_first_n = 0
threshold = 3
